function dMdt = solve_ODEs_network_v0_2(t,tspan,n_datapoints,dt,M,scaling,plastic_type,...
    intervention_t_start, intervention_t_end, equation_or_timeseries,arrow_timeseries,...
    relative_absolute, a,b,c,d,box_total_capacity, box_flow_capacity, box_flow_capacity_t_start, box_flow_capacity_t_end,...
    box_capacity_t_start, box_capacity_t_end,...
    production_interaction, production_rates, imports_interaction, exports_interaction, imports_rates, waste_generated_box_number,...
    n_stocks,n_flows,max_annual_flow_rate,...
    n_inflows, n_outflows,...
    in_interaction_number,in_index,in_source,...
    out_interaction_number,out_index,out_source,...
    enforced_proportion, processing_rate,...
    stock_stock_interactions,flow_flow_interactions,plug, function_type, mc, call_origin, zone_proportions,...
    z, finite_sinks, micro, macro, baseline_run, baseline_individual_flow)

global box_active;

[in_flow, out_flow, ~] = calc_flows(M,t,tspan,n_datapoints,dt,scaling,...
    n_stocks,n_flows,plastic_type,stock_stock_interactions,...
    intervention_t_start, intervention_t_end, equation_or_timeseries,arrow_timeseries,...
    relative_absolute,a,b,c,d,box_total_capacity,box_flow_capacity, box_flow_capacity_t_start, box_flow_capacity_t_end,...
    box_capacity_t_start, box_capacity_t_end,...
    production_interaction, production_rates, imports_interaction, exports_interaction, imports_rates, waste_generated_box_number,...
    plug, function_type, enforced_proportion, processing_rate,max_annual_flow_rate,...
    flow_flow_interactions, in_interaction_number, out_interaction_number,...
    n_inflows, n_outflows, in_index, in_source, out_source, out_index, mc, call_origin, zone_proportions,...
    z, finite_sinks, micro, macro, baseline_run, baseline_individual_flow);

dMdt = in_flow - out_flow;


end